### ISSUE TITLE
Unable to add new integration due to getmacbyip failure

### ISSUE THREAD

**Issue by ngrusz1** [pauln/tailwind-home-assistant#26]
I just set up a new Tailwind iQ3 device and successfully connected it to my network. I am able to access it via the web.gotailwind.com website. When I try to add it to my HA server, I get an error stating "IP address is invalid (MAC address could not be determined). Please correct it and try again."  When I check my HA logs, I note the following additional error message:

Logger: scapy.runtime
Source: custom_components/tailwind_iq3/config_flow.py:53
Integration: Tailwind iQ3
First occurred: 2:05:11 PM (1 occurrences)
Last logged: 2:05:11 PM

getmacbyip failed on [Errno 1] Operation not permitted

Any ideas? I am currently running HA version 2023.12.1 on python 3.11.

**Comment by ngrusz1** [comment]
I figured out what was causing this issue, and I wonder if there's something that can be added to prevent it in the future for others. The issue was a permissions error. My HA instance is run under its own user (in this case, the "homeassistant" user). Apparently this user does not have permission to access the getmacbyip function/package. Temporarily running my HA instance as root fixed the problem -- I was able to add my Tailwind device without issue. It's obviously a terrible idea to run your HA server as the root user so once I added my Tailwind device I reverted back to running HA as my regular user, and everything seems fine -- the Tailwind device is still present and appears to work. I will note that changing the user to root and back was not without its own issues; starting my HA instance as the root user changed the owner and access permissions on a bunch of internal HA files, and I needed to find and revert these as well so my server would run properly under my regular user.

It seems like the only purpose of the getmacbyip function is to find the MAC address that's associated with the Tailwind controller during the initial setup, correct? If so, would it be possible to modify the integration such that if it is unable to automatically determine the MAC address based on the user-provided IP address, it then presents the user with the option of defining the MAC address manually?

**Comment by pauln** [comment]
I'm glad to hear that you've figured it out and got the integration up and running.  The MAC address is used to generate a unique device ID which matches that provided via the mDNS discovery process, so that it doesn't get discovered as a new device after you've manually configured it.

This integration still makes use of the original "command API", which is very basic and only provides a way to open/close a door or get the status of all doors; a JSON API was subsequently added in another firmware update, which provides more detail (and a bit more control, such as the ability to do timed "partial open" commands and set the status LED brightness) - including the MAC address (albeit in a slightly odd format).  I'll try to find time to shift over to the JSON API - and as part of that process, switch to extracting the MAC address from the status response rather than having to do a lookup (which, as you've found, may fail for various reasons, even if the device's API is reachable).

**Comment by SmashFactory18** [comment]
I am running into the same issue trying to set up this integration. I am new to home assistant and running it through docker on unraid. I know just enough to get myself in trouble so im not sure how id give this container more privileges but I am mostly commenting to let you know if you made these changes it would help out at least one more person.

**Comment by pauln** [comment]
I've just released v0.6.0 of the integration, which shifts to the JSON API - and with that, removes the dependency on `scapy` and its `getmacbyip`.  If you update to v0.6.0 (or install it, if you've removed the previous version), you should hopefully now be able to set up (and use) the integration without needing to adjust your HA container's privileges.
