### ISSUE TITLE
discovery_info['host'] vs. discovery_info.host

### ISSUE THREAD

**Issue by ryanpowers** [pauln/tailwind-home-assistant#3]
Just wanted to let you know about a message in the logs about deprecated functionality to be removed in the near-ish future.

> Detected integration that accessed discovery_info['host'] instead of discovery_info.host; this will fail in version 2022.6. Please report issue to the custom component author for tailwind_iq3 using this method at custom_components/tailwind_iq3/config_flow.py, line 97: self._ip_address = discovery_info[CONF_HOST]

Probably low priority. I am very new to HA (haven't actually gotten this integration running yet), but came across that log message when trying to get things setup.

**Comment by pauln** [comment]
Thanks - I spotted this in the release notes for HA 2021.12, but hadn't looked into it properly yet since it's only a deprecation at this point.  Since there's a ~6 month lead time on the deprecation, it is indeed pretty low priority; at this stage, I'll aim to address this when I update this component in preparation for the firmware update's full release (hopefully Tailwind are able to get that sorted before too much longer).

**Comment by pauln** [comment]
I've addressed this deprecation as part of v0.2.0, which I've just released to support the V9.95 firmware (which unexpectedly added the Local Control Key).  Please see the README in this repo for upgrade notes - you'll need to remove and re-add the integration after updating the custom component (via HACS or manually, depending on how you installed it) in order to add your Local Control Key.
